name: Release
on:
  push:
    tags:
      - "release-v*"

jobs:
  release-to-gitHub:
    name: Release to github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Asseble release
        run: |
          ./gradlew app:assembleRelease --info
          cp app/build/outputs/apk/release/app-release.apk release.apk
          ls|grep apk
      - name: Upload
        uses: stefanji/action-gh-release@releases/test
        with:
          files: release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
